name: Sonar Qube on push to master

on:
  push:
    branches:
      - master

jobs:
  phpunit-with-sonar-qube:
    uses: BrandEmbassy/github-actions/.github/workflows/php-phpunit-with-sonar-qube.yml@master
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      PHP_VERSION: '8.2'
